{
  config,
  pkgs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    alacritty
    alejandra
    android-tools
    appimage-run
    bato
    borgbackup
    bottles
    brightnessctl
    calibre
    cargo
    chromium
    clang
    clippy
    conda
    cryptsetup
    delta
    diesel-cli
    discord
    evince
    exiftool
    feh
    firejail
    fish
    flameshot
    font-awesome
    gh
    gimp
    git
    glow
    google-chrome
    gparted
    helix
    home-manager
    htop
    inkscape
    just
    kdePackages.kcalc
    keepassxc
    kitty
    koto
    koto-ls
    libnotify
    libreoffice
    libxkbcommon
    lldb
    mkvtoolnix-cli
    monitor
    mpv
    mscp
    mullvad-vpn
    nautilus
    neofetch
    nodejs
    nodePackages.live-server
    nvtopPackages.full
    obsidian
    openrazer-daemon
    openssl
    pandoc
    pavucontrol
    pdftk
    pkg-config
    playerctl
    pnpm
    progress
    protobuf
    pulseaudio
    python314
    rio
    rust-analyzer
    rustc
    rustfmt
    signal-desktop
    sqlite
    tinymist
    tokei
    transmission_4-qt
    tty-clock
    typst
    typstyle
    unzip
    upscayl
    vim
    wasm-bindgen-cli
    xdragon
    xorg.xev
    xsel
    yad
    yazi
    yt-dlp
    zellij
    (vscode-with-extensions.override {
      vscode = vscodium;
      vscodeExtensions = with vscode-extensions;
        [
          vadimcn.vscode-lldb
          jnoortheen.nix-ide
          rust-lang.rust-analyzer
          foam.foam-vscode
          bierner.emojisense
          ms-python.python
          tamasfe.even-better-toml
          zxh404.vscode-proto3
          bradlc.vscode-tailwindcss
          tomoki1207.pdf
          streetsidesoftware.code-spell-checker
          streetsidesoftware.code-spell-checker-german
        ]
        ++ pkgs.vscode-utils.extensionsFromVscodeMarketplace [
          {
            name = "doki-theme";
            publisher = "unthrottled";
            version = "88.1.15";
            sha256 = "ys3D84zg7mGGTG5Ey65gqgujbUJBsg27MC3qUnbluoM=";
          }
        ];
    })
    gnomeExtensions.unite
  ];
}
