# custom bg
background_image               ~/git/nixos/aesthetics/ene_c-0.01.png
background_image_layout        cscaled

# f1 to open scrollback buffer in nvim
map f1 launch --stdin-source=@screen_scrollback --type=overlay nvim
